/**
 * Pre-baked Experience particle targets (warehouse + Haas press).
 * Generated by `node scripts/bake-experience.mjs` — runtime never loads the source GLBs.
 */

export type ExperienceBakedId = 'warehouse' | 'haasPress';

export type ExperienceBakedShape = {
  positions: Float32Array;
  colors: Float32Array;
  sizes: Float32Array;
  /** Haas press only — looping position frames */
  animFrames?: Float32Array[];
  animDuration?: number;
};

const N = 34_000;
const FLOATS = N * 3;

async function loadBin(url: string): Promise<Float32Array> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to load ${url}`);
  const buf = await res.arrayBuffer();
  return new Float32Array(buf);
}

let cache: Partial<Record<ExperienceBakedId, ExperienceBakedShape>> | null = null;

export async function loadExperienceBaked(id: ExperienceBakedId): Promise<ExperienceBakedShape> {
  if (cache?.[id]) return cache[id]!;

  const base = `/particle-targets/experience/${id}`;
  const v = 'v=20260910exp2';
  const [positions, colors, sizes] = await Promise.all([
    loadBin(`${base}.bin?${v}`),
    loadBin(`${base}_colors.bin?${v}`),
    loadBin(`${base}_sizes.bin?${v}`),
  ]);

  if (positions.length !== FLOATS) {
    console.warn(`[experience] ${id} positions ${positions.length}, expected ${FLOATS}`);
  }

  const shape: ExperienceBakedShape = { positions, colors, sizes };

  if (id === 'haasPress') {
    const [anim, metaRes] = await Promise.all([
      loadBin(`${base}_anim.bin?${v}`),
      fetch(`${base}_meta.json?${v}`),
    ]);
    const meta = metaRes.ok
      ? ((await metaRes.json()) as { frames: number; duration: number })
      : { frames: Math.round(anim.length / FLOATS), duration: 4.17 };
    const frames: Float32Array[] = [];
    for (let f = 0; f < meta.frames; f++) {
      frames.push(anim.subarray(f * FLOATS, (f + 1) * FLOATS));
    }
    shape.animFrames = frames;
    shape.animDuration = meta.duration;
  }

  if (!cache) cache = {};
  cache[id] = shape;
  return shape;
}

export function preloadExperienceBaked(): Promise<unknown> {
  return Promise.all([loadExperienceBaked('warehouse'), loadExperienceBaked('haasPress')]).catch(
    (err) => {
      console.warn('[experience] bake preload failed', err);
    },
  );
}
