/**
 * Pre-baked Vendor Registration particle targets.
 * Generated by `node scripts/bake-vendors.mjs` — runtime never loads the source GLBs.
 */

export type VendorBakedId = 'logo' | 'forklift' | 'handshake';

export type VendorBakedShape = {
  positions: Float32Array;
  colors: Float32Array;
  sizes: Float32Array;
  /** Forklift only — looping position frames */
  animFrames?: Float32Array[];
  animDuration?: number;
};

const N = 16_000;
const FLOATS = N * 3;

async function loadBin(url: string): Promise<Float32Array> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to load ${url}`);
  const buf = await res.arrayBuffer();
  return new Float32Array(buf);
}

let cache: Partial<Record<VendorBakedId, VendorBakedShape>> | null = null;

export async function loadVendorBaked(id: VendorBakedId): Promise<VendorBakedShape> {
  if (cache?.[id]) return cache[id]!;

  // Cache-bust when bins are rebaked (in-memory cache still needs a remount/hard reload).
  const base = `/particle-targets/vendors/${id}`;
  const v = 'v=20260910fork2';
  const [positions, colors, sizes] = await Promise.all([
    loadBin(`${base}.bin?${v}`),
    loadBin(`${base}_colors.bin?${v}`),
    loadBin(`${base}_sizes.bin?${v}`),
  ]);

  if (positions.length !== FLOATS) {
    console.warn(`[vendors] ${id} positions ${positions.length}, expected ${FLOATS}`);
  }

  const shape: VendorBakedShape = { positions, colors, sizes };

  if (id === 'forklift') {
    const [anim, metaRes] = await Promise.all([
      loadBin(`${base}_anim.bin?${v}`),
      fetch(`${base}_meta.json?${v}`),
    ]);
    const meta = metaRes.ok
      ? ((await metaRes.json()) as { frames: number; duration: number })
      : { frames: Math.round(anim.length / FLOATS), duration: 2.67 };
    const frames: Float32Array[] = [];
    for (let f = 0; f < meta.frames; f++) {
      frames.push(anim.subarray(f * FLOATS, (f + 1) * FLOATS));
    }
    shape.animFrames = frames;
    shape.animDuration = meta.duration;
  }

  if (!cache) cache = {};
  cache[id] = shape;
  return shape;
}

/** Warm the three Vendor baked shapes (nav hover / route preload). */
export function preloadVendorBaked(): Promise<unknown> {
  return Promise.all([
    loadVendorBaked('logo'),
    loadVendorBaked('forklift'),
    loadVendorBaked('handshake'),
  ]).catch((err) => {
    console.warn('[vendors] bake preload failed', err);
  });
}
